### ISSUE TITLE
关于安装报错

### ISSUE THREAD

**Issue by Ran-Xing** [FeeiCN/Cobra#1398]
https://blog.csdn.net/k417699481/article/details/110727648

升级修复 原问题链接
该错误已在werkzeug 0.15.5中修复。从0.15.4升级到更高版本。
```
Flask==1.0.0
Flask-RESTful==0.3.6
rarfile==2.7
prettytable==0.7.2
requests==2.20.0
pytest==3.0.6
pip==9.0.1
phply==1.0.0
Werkzeug==0.15.5
ConcurrentLogHandler==0.9.1

```
不用谢我是好人

**Comment by pasalai** [comment]
python3.8 审计出错clone这个分支git clone https://github.com/banbooboo/Cobra.git
